security:
  user:
    password: password
spring:
  session:
    redis:
      flush-mode: immediate
      namespace: spring:session
    store-type: redis
  redis:
    host: localhost
    password: password
    port: 6379
zuul:
  routes:
    resource:
      path: /api/**
      url: http://localhost:9000/api
      sensitiveHeaders: