version: '2'
networks:
  app-tier:
    driver: bridge
services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password
    volumes:
      - '/Users/mishrav/Softwares/cloud_computing:/bitnami'
    networks:
      - app-tier

  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=i3core
      - REDIS_PASSWORD=i3core
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    networks:
      - app-tier
