server:
  port: 8084
zuul:
  sensitive-headers:
  routes:
    resource:
      path: /api/**
      url: http://localhost:9000/api
    ui:
      url: http://localhost:8082
security:
  user:
    password:
      password
  sessions: ALWAYS
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    password: password
    port: 6379
    namespace: spring:session