server:
  port: 8084
zuul:
  routes:
    resource:
      path: /api/**
      url: http://localhost:9000/api
      sensitive-headers:
    ui:
      url: http://localhost:8082
      sensitive-headers:
    admin:
      url: http://localhost:8083
      sensitive-headers:
security:
  sessions: ALWAYS
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    password: password
    port: 6379
    namespace: spring:session